on:
  push:
    branches:
      - main

jobs:
  clusterawsadm:
    environment: AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
    
    - name: Set up Go 
      uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
      with:
        go-version: 1.17
        
    - name: Test clusterawsadm using Go
      run: |
        git clone https://github.com/kubernetes-sigs/image-builder.git
        cd image-builder/images/capi
        make deps-ami
        cd ../../..
        go run main.go
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
